# list the data broker peers for the server under [[DBs]] table

# PubKeyBase64: public key for the data broker in base64 format.
# ExpireTime (epoch timestamp in seconds): peer key validation will fail when it expires.
[[DBs]]
PubKeyBase64 = "CtxNuy7lJ1mJgjqWplcwN8dZhXhSNPhECja1A0OWKa+2wtI7xuB3jPcamogGZGBBfQ4SqnoPGLA7zRQaAotoxg=="
ExpireTime = 1924991999
